# Generated by Django 3.1.5 on 2021-02-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20210202_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='iamge',
            new_name='image',
        ),
    ]
